swagger: '2.0'

info:
  version: "0.0.1"
  title: Ping Pong Service

paths:
  /ping:
    get:
      description: |
        We pong to your ping
      produces:
        - text/plain
      responses:
        200:
          description: We ponged you good.
          schema:
            type: string